/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.algoritmos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tipografias.Fuentes;

//librerias para exportar en excel
import java.io.*;
//import java.util.*;
import javax.swing.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.hssf.usermodel.*;
import org.apache.poi.xssf.usermodel.*;

//librerias que deberian ir en el controlador de excel
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dark_
 */
public class congruencialMultiplicativo extends javax.swing.JInternalFrame {

    // --- VARIABLES ------------crea variables para el modelo de la tabla y el tipo de fuente del formulario

    private final Fuentes tipoFuente; // para llamar el metodo de tipografias personalizadas
    private DefaultTableModel modelo; // se crea modelo para tabla
    private DefaultTableModel modelo2; // se crea modelo2 para tabla 2
    
    Workbook wb; // para trabajar importar y/o exportar archivos en xls
    
    JFileChooser selecArchivo = new JFileChooser();
    File archivo;
    int contAccion = 0;
    
    public congruencialMultiplicativo() {
        initComponents();
        
        // SE PERSONALIZA TODO EL TEXTO CON FUENTES DEL PAQUETE TIPOGRAFIA
        tipoFuente = new Fuentes(); // crea tipo de fuente para usar atributos y procedimientos
        ///----------------///----- ETIQUETAS -----///---------------///
        etiq_tituloCongruencialMultiplicativo_.setFont(tipoFuente.fuente(tipoFuente.GOD,0,24));
        ///----------------///----- BOTONES -----///---------------///
        btn_calcularA_.setVisible(false);
        btn_calcularK_.setVisible(false);
        ///----------------///----- TABLA MENU -----///---------------///
        tabla_congruencialMultiplicativo_.setEnabled(false);
        tabla_numerosAleatorios_.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq_tituloCongruencialMultiplicativo_ = new javax.swing.JLabel();
        etiq_semilla_ = new javax.swing.JLabel();
        txt_semilla_ = new javax.swing.JTextField();
        etiq_constanteK_ = new javax.swing.JLabel();
        etiq_a_ = new javax.swing.JLabel();
        txt_a_ = new javax.swing.JTextField();
        txt_constanteK_ = new javax.swing.JTextField();
        btn_calcularA_ = new javax.swing.JButton();
        btn_calcularK_ = new javax.swing.JButton();
        etiq_m_ = new javax.swing.JLabel();
        etiq_g_ = new javax.swing.JLabel();
        txt_g_ = new javax.swing.JTextField();
        txt_m_ = new javax.swing.JTextField();
        btn_calcularG_ = new javax.swing.JButton();
        btn_calcularM_ = new javax.swing.JButton();
        btn_calcular_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_congruencialMultiplicativo_ = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_numerosAleatorios_ = new javax.swing.JTable();
        btn_exportar_ = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        etiq_tituloCongruencialMultiplicativo_.setText("CONGRUENCIAL MULTIPLICATIVO");

        etiq_semilla_.setText("Semilla:");

        etiq_constanteK_.setText("Constante K:");

        etiq_a_.setText("A:");

        btn_calcularA_.setText("Calcular A");
        btn_calcularA_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularA_ActionPerformed(evt);
            }
        });

        btn_calcularK_.setText("Calcular K");
        btn_calcularK_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularK_ActionPerformed(evt);
            }
        });

        etiq_m_.setText("M:");

        etiq_g_.setText("G:");

        btn_calcularG_.setText("Calcular G");
        btn_calcularG_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularG_ActionPerformed(evt);
            }
        });

        btn_calcularM_.setText("Calcular M");
        btn_calcularM_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularM_ActionPerformed(evt);
            }
        });

        btn_calcular_.setText("Calcular");
        btn_calcular_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_ActionPerformed(evt);
            }
        });

        tabla_congruencialMultiplicativo_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "X"
            }
        ));
        jScrollPane1.setViewportView(tabla_congruencialMultiplicativo_);

        tabla_numerosAleatorios_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "R"
            }
        ));
        jScrollPane2.setViewportView(tabla_numerosAleatorios_);

        btn_exportar_.setText("EXPORTAR a EXCEL");
        btn_exportar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportar_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiq_tituloCongruencialMultiplicativo_)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiq_constanteK_)
                                        .addGap(14, 14, 14)
                                        .addComponent(txt_constanteK_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiq_a_)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_a_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiq_semilla_)
                                .addGap(19, 19, 19)
                                .addComponent(txt_semilla_, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_calcularA_)
                            .addComponent(btn_calcularK_, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiq_m_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_m_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_calcularG_))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(etiq_g_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_g_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_calcularM_)))))
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btn_calcular_)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btn_exportar_)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiq_tituloCongruencialMultiplicativo_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_semilla_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiq_semilla_))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_constanteK_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_constanteK_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_a_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_a_)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_m_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_m_)
                            .addComponent(btn_calcularG_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_g_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_calcularM_)
                            .addComponent(etiq_g_)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_calcularA_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_calcularK_)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_calcular_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exportar_)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularA_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularA_ActionPerformed
        /*if ( validarIndividual( txt_constanteK_.getText() ) ) {
            int a = 1+( 4*Integer.parseInt( txt_constanteK_.getText() ) );
            txt_a_.setText(String.valueOf(a));
        } else {
            JOptionPane.showMessageDialog(rootPane, " Debe existir la variable K ");
        }*/
    }//GEN-LAST:event_btn_calcularA_ActionPerformed

    private void btn_calcularK_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularK_ActionPerformed
        /*if ( validarIndividual( txt_a_.getText() ) ) {
            int k = ( Integer.parseInt( txt_a_.getText() ) - 1 )/4;
            txt_constanteK_.setText(String.valueOf(k));
        } else {
            JOptionPane.showMessageDialog(rootPane, " Debe existir la variable A ");
        }*/
    }//GEN-LAST:event_btn_calcularK_ActionPerformed

    private void btn_calcularG_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularG_ActionPerformed
        if ( validarIndividual( txt_m_.getText() ) ) { // Math.log10(num) / Math.log10(base)

            double log = Math.log10( Integer.parseInt(txt_m_.getText()) ) / Math.log10(2);

            //System.out.println(" lo que esta en log "+log+" pasado a entero "+ logInt);
            if (  log - Math.floor( log ) == 0 ) {

                int logInt = (int) log;

                txt_g_.setText( String.valueOf(logInt) );

            } else {

                JOptionPane.showMessageDialog( rootPane, " La variable M es ERRONEA ya que G debe ser entero y da como resultado: "+log );

            }

        } else {
            JOptionPane.showMessageDialog(rootPane, " Debe existir la variable M ");
        }
    }//GEN-LAST:event_btn_calcularG_ActionPerformed

    private void btn_calcularM_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularM_ActionPerformed
        if ( validarIndividual( txt_g_.getText() ) ) {
            double g = Double.parseDouble( txt_g_.getText());

            if (  g - Math.floor( g ) == 0 ) {
                System.out.println(" dice q g es entero "+g);
                int m = (int) Math.pow(2,g);
                System.out.println(" int m casteado "+m);
                txt_m_.setText( String.valueOf(m) );
            } else {

                JOptionPane.showMessageDialog( rootPane, " La variable M no se puede calcular ya que G debe ser entero y da como resultado: "+g );
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, " Debe existir la variable G ");
        }
    }//GEN-LAST:event_btn_calcularM_ActionPerformed

    private void btn_calcular_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_ActionPerformed
        if ( validarTxtVacios() && validarTxtNumericos() && validarTxtPositivos()  ) {
            
            
            int a = Integer.parseInt( txt_a_.getText() ); // SI GENERA ERROR CON VALORES FLOTANTES ES MEJOR CASTEAR (int)
            int m = Integer.parseInt( txt_m_.getText() );
            //int g = Integer.parseInt( txt_g_.getText() );
            int semilla = Integer.parseInt( txt_semilla_.getText() );
            //int k = Integer.parseInt( txt_constanteK_.getText() );
            
            boolean impar = false;
            
            if(semilla%2==0){
                System.out.println(a+" es par");
            }else{
                System.out.println(a+" es impar");
                impar = true;
            }  
            
            if(impar){
                
                int finFilas = 2;

                modelo = new DefaultTableModel();
                modelo2 = new DefaultTableModel();
                tabla_congruencialMultiplicativo_.setModel(modelo);
                tabla_numerosAleatorios_.setModel(modelo2);

                modelo.addColumn("#");
                modelo.addColumn("X");

                modelo2.addColumn("#");
                modelo2.addColumn("R");

                //llenar la tabla con la fila de objetos
                for(int fila=0;fila<finFilas;fila++){ // recorrido de filas

                    String sNumeros[] = new String[2]; // convierte en cadenas para parasarlos al modelo de la tabla
                    String sNumeros2[] = new String[2]; // convierte en cadenas para parasarlos al modelo de la tabla

                    for(int col=0;col<5;col++){ // recorrido de columnas
                        System.out.println("fila "+fila+" columna "+col);
                        switch(col) {
                            case 0:// la columna del numero
                            sNumeros[col] = String.valueOf( fila+1 );
                            //System.out.println("valor en arreglo "+sNumeros[col]);
                            break;
                            case 1:// la columna del numero x o semillas
                            if(fila==0){
                                int x = ((a*semilla))%m;
                                sNumeros[col] = String.valueOf(x);
                                System.out.println("valor en arreglo "+sNumeros[col]);
                            }else{
                                int x = (a*Integer.parseInt( modelo.getValueAt(fila-1, col).toString() ))%m;
                                sNumeros[col] = String.valueOf(x);
                                System.out.println("valor en arreglo "+sNumeros[col]);
                            }
                            break;
                            case 2: // la columna del numero
                            sNumeros2[0] = String.valueOf(fila+1);
                            System.out.println("valor en arreglo "+sNumeros2[0]);
                            break;
                            case 3: // la columna del numero r

                            float r = Float.parseFloat(sNumeros[1] )/(m-1);
                            sNumeros2[1] = String.valueOf(r);
                            System.out.println("valor en arreglo "+sNumeros2[1]);

                            break;
                            default:
                            // code block
                        }
                    }

                    modelo.addRow(sNumeros); //agregando datos a la fila

                    modelo2.addRow(sNumeros2); //agregando datos a la fila

                    // verificar numero repetidos
                    int rep = 0;
                    if(fila > 0){
                        for(int i=0;i<modelo.getRowCount()-1;i++){
                            System.out.println(" valor i "+i+" cantidad filas "+modelo.getRowCount());
                            System.out.println(" valor de fila "+fila+" columna 1 "+modelo.getValueAt(i, 1));
                            System.out.println(" valor del array en columna 1 "+sNumeros[1]);
                            if ( modelo.getValueAt(i,1).toString().equals(sNumeros[1]) ) {
                                System.out.println(" encontro un repetido");
                                rep++;
                            } else {
                                System.out.println("NO encontro un repetido");
                                finFilas++;
                            }
                        }
                    }
                    if(rep>0){
                        break;
                    }

                } 
            }else{
                JOptionPane.showMessageDialog(rootPane, " Para calcular la semilla debe ser un numero entero IMPAR ");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, " Las casillas deben estar llenas, ser numericas y positivas ");
        }

    }//GEN-LAST:event_btn_calcular_ActionPerformed

    private void btn_exportar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportar_ActionPerformed

        contAccion++;
        if( contAccion == 1 ){ agregarFiltro(); }

        if( selecArchivo.showDialog( null, "Exportar" ) == JFileChooser.APPROVE_OPTION ){
            archivo = selecArchivo.getSelectedFile();
            if( archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")  ){
                JOptionPane.showMessageDialog(null, exportar(archivo, tabla_numerosAleatorios_ ) );
            }else{
                JOptionPane.showMessageDialog(null, "Digite al final del nombre del archivo un formato EXCEL valido. Ejemplo ( archivo.xls o archivo.xlsx )." );
            }
        }
    }//GEN-LAST:event_btn_exportar_ActionPerformed
    
    // ----------- FUNCIONES Y PROCEDIMIENTOS -------------------------------------------/////////////////////////////////

    public String exportar(File archivo, JTable tablaD){
        String respuesta = "No se realizo con exito la exportacion";
        
        int numFila = tablaD.getRowCount(), numColumna = tablaD.getColumnCount();
        
        if( archivo.getName().endsWith("xls") ){
            wb = new HSSFWorkbook();
        }else{
            wb = new XSSFWorkbook();
        }
        
        Sheet hoja = wb.createSheet("congruencialMultiplicativo");
        
        try{           
            for (int i = -1; i < numFila; i++) {               
                Row fila = hoja.createRow(i+1);               
                for (int j = 0; j < numColumna; j++) {                   
                    Cell celda = fila.createCell(j);                   
                    if (i==-1) {                       
                        celda.setCellValue( String.valueOf( tablaD.getColumnName(j) ) );                     
                    } else {                     
                        celda.setCellValue( String.valueOf( tablaD.getValueAt(i, j) ) );                     
                    }                   
                    wb.write(new  FileOutputStream(archivo) );
                }
            }           
            respuesta = "Exportacion exitosa";
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "Error al exportar archivo excel: -> "+e);
        }
        
        return respuesta;  
    }
    
    public void agregarFiltro(){     
        selecArchivo.setFileFilter( new FileNameExtensionFilter( "Excel (*.xls)","xls" )  );
        selecArchivo.setFileFilter( new FileNameExtensionFilter( "Excel (*.xlsx)","xlsx" )  );       
    }
    
    private  boolean validarTxtVacios(){
        boolean vacio = true;
      
        if( txt_a_.getText().isEmpty() ) return false;
        if( txt_g_.getText().isEmpty() ) return false;
        if( txt_m_.getText().isEmpty() ) return false;
        if( txt_semilla_.getText().isEmpty() ) return false;
        if( txt_constanteK_.getText().isEmpty() ) return false;

        return vacio;
    }
    
    private  boolean validarTxtPositivos(){
        boolean vacio = true;
      
        if( Integer.parseInt(txt_a_.getText()) < 0 ) return false;
        if( Integer.parseInt(txt_g_.getText()) < 0 ) return false;
        if( Integer.parseInt(txt_m_.getText()) < 0 ) return false;
        if( Integer.parseInt(txt_semilla_.getText()) < 0 ) return false;
        if( Integer.parseInt(txt_constanteK_.getText()) < 0 ) return false;

        return vacio;
    }
    
    private  boolean validarTxtNumericos(){
        boolean vacio = true;
     
        if( !isNumeric( txt_a_.getText()) ) return false;
        if( !isNumeric( txt_g_.getText()) ) return false;
        if( !isNumeric( txt_m_.getText()) ) return false;
        if( !isNumeric( txt_semilla_.getText()) ) return false;
        if( !isNumeric( txt_constanteK_.getText()) ) return false;

        return vacio;
    }
    
    private static boolean validarIndividual( String validar ){
        boolean valido = true;
        
        if( !isNumeric( validar ) ) return false;
        if( Integer.parseInt( validar ) < 0 ) return false;
        if( validar.isEmpty() ) return false;
        
        return valido;
    }
    
    private static boolean isNumeric(String cadena) // se certifica con esto de que sean numeros en la celda de la tabla
    {
        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcularA_;
    private javax.swing.JButton btn_calcularG_;
    private javax.swing.JButton btn_calcularK_;
    private javax.swing.JButton btn_calcularM_;
    private javax.swing.JButton btn_calcular_;
    public javax.swing.JButton btn_exportar_;
    private javax.swing.JLabel etiq_a_;
    private javax.swing.JLabel etiq_constanteK_;
    private javax.swing.JLabel etiq_g_;
    private javax.swing.JLabel etiq_m_;
    private javax.swing.JLabel etiq_semilla_;
    private javax.swing.JLabel etiq_tituloCongruencialMultiplicativo_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_congruencialMultiplicativo_;
    private javax.swing.JTable tabla_numerosAleatorios_;
    private javax.swing.JTextField txt_a_;
    private javax.swing.JTextField txt_constanteK_;
    private javax.swing.JTextField txt_g_;
    private javax.swing.JTextField txt_m_;
    private javax.swing.JTextField txt_semilla_;
    // End of variables declaration//GEN-END:variables
}
