/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import tipografias.Fuentes;

/**
 *
 * @author dark_
 */
public class DESPEDIDA extends javax.swing.JFrame {

    private final Fuentes tipoFuente; // para llamar el metodo de tipografias personalizadas
    
    public DESPEDIDA() {
        initComponents();
        tipoFuente = new Fuentes(); // crea tipo de fuente para usar atributos y procedimientos
        ///----------------///--------------------///---------------///
        Etiq_Gracias_.setFont(tipoFuente.fuente(tipoFuente.GOD,0,36));
        //Etiq_Gracias_.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel_FondoGracias_ = new javax.swing.JPanel();
        Etiq_Gracias_ = new javax.swing.JLabel();
        Etiq_fondo_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel_FondoGracias_.setBackground(new java.awt.Color(102, 102, 102));

        Etiq_Gracias_.setForeground(new java.awt.Color(255, 153, 51));
        Etiq_Gracias_.setText("GRACIAS");

        javax.swing.GroupLayout JPanel_FondoGracias_Layout = new javax.swing.GroupLayout(JPanel_FondoGracias_);
        JPanel_FondoGracias_.setLayout(JPanel_FondoGracias_Layout);
        JPanel_FondoGracias_Layout.setHorizontalGroup(
            JPanel_FondoGracias_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_FondoGracias_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Etiq_Gracias_)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        JPanel_FondoGracias_Layout.setVerticalGroup(
            JPanel_FondoGracias_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_FondoGracias_Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Etiq_Gracias_)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(JPanel_FondoGracias_, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 210, 70));

        Etiq_fondo_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pug adios.gif"))); // NOI18N
        getContentPane().add(Etiq_fondo_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
             
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        Etiq_Gracias_.setVisible(true);
        Thread mith = Thread.currentThread(); // cuando se de click al jframe cuenta y se cierra el mismo  
        try{
            mith.sleep(500);
            System.exit(0);
        }catch(InterruptedException ie){
            System.err.println(" Capturada Interrupted Exception "+ie);
        }  
    }//GEN-LAST:event_formMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DESPEDIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DESPEDIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DESPEDIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DESPEDIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DESPEDIDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiq_Gracias_;
    private javax.swing.JLabel Etiq_fondo_;
    private javax.swing.JPanel JPanel_FondoGracias_;
    // End of variables declaration//GEN-END:variables
}
