/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.pruebas;

import javax.swing.JOptionPane;
import tipografias.Fuentes;

//librerias para exportar en excel
import java.io.*;
//import java.text.DecimalFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
//import org.apache.poi.hssf.usermodel.*;
//import org.apache.poi.xssf.usermodel.*;

//librerias que deberian ir en el controlador de excel
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dark_
 */
public class media extends javax.swing.JInternalFrame {
    
      // --- VARIABLES ------------crea variables para el modelo de la tabla y el tipo de fuente del formulario

    private final Fuentes tipoFuente; // para llamar el metodo de tipografias personalizadas
    
    Workbook wb; // para trabajar importar y/o exportar archivos en xls
    
    JFileChooser selecArchivo = new JFileChooser();
    File archivo;
    int contAccion = 0;
    double resultadoGlobal;
    
    /**
     * Creates new form media
     */
    public media() {
        initComponents();
        
        // SE PERSONALIZA TODO EL TEXTO CON FUENTES DEL PAQUETE TIPOGRAFIA
        tipoFuente = new Fuentes(); // crea tipo de fuente para usar atributos y procedimientos
        ///----------------///----- ETIQUETAS -----///---------------///
        etiq_tituloMedia_.setFont(tipoFuente.fuente(tipoFuente.GOD,0,24));
        etiq_resultado_.setFont(tipoFuente.fuente(tipoFuente.GOD,0,18));
        etiq_resultado_.setVisible(false);
        etiq_aceptacion_.setVisible(false);
        etiq_info_.setVisible(false);
        etiq_info2_.setVisible(false);
        ///----------------///----- TABLAS -----///---------------///
        tabla_numerosAleatorios_.setVisible(false); 
        ///----------------///----- TEXTO -----///---------------///
        txt_aceptacion_.setVisible(false); 
        ///----------------///----- BOTONES -----///---------------///
        btn_calcular_.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq_tituloMedia_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_numerosAleatorios_ = new javax.swing.JTable();
        btn_importar_ = new javax.swing.JButton();
        etiq_aceptacion_ = new javax.swing.JLabel();
        txt_aceptacion_ = new javax.swing.JTextField();
        btn_calcular_ = new javax.swing.JButton();
        etiq_resultado_ = new javax.swing.JLabel();
        etiq_info_ = new javax.swing.JLabel();
        etiq_info2_ = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        etiq_tituloMedia_.setText("MEDIA");

        tabla_numerosAleatorios_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_numerosAleatorios_.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_numerosAleatorios_);

        btn_importar_.setText("IMPORTAR desde EXCEL");
        btn_importar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importar_ActionPerformed(evt);
            }
        });

        etiq_aceptacion_.setText("Nivel de aceptacion: ");

        btn_calcular_.setText("Calcular");
        btn_calcular_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_ActionPerformed(evt);
            }
        });

        etiq_resultado_.setText("resultado");

        etiq_info_.setText("Niveles mas usados -> 80% = 1.28, 85% = 1.44, 90% = 1.65");

        etiq_info2_.setText("Niveles mas usados -> 95% = 1.96, 85% = 1.44, 99% = 2.58");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_tituloMedia_)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiq_aceptacion_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_aceptacion_, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_calcular_))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btn_importar_))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(etiq_resultado_))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiq_info_))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiq_info2_)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(etiq_tituloMedia_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_importar_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiq_info_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq_info2_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_aceptacion_)
                    .addComponent(txt_aceptacion_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular_))
                .addGap(18, 18, 18)
                .addComponent(etiq_resultado_)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_importar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importar_ActionPerformed

        contAccion++;
        if( contAccion == 1 ){ agregarFiltro(); }

        if( selecArchivo.showDialog(null, "Seleccionar archivo" ) == JFileChooser.APPROVE_OPTION ){
            archivo = selecArchivo.getSelectedFile();
            if ( archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")  ) {
                JOptionPane.showMessageDialog(null, importar( archivo, tabla_numerosAleatorios_ ) );
            } else {
                JOptionPane.showMessageDialog( null, "Elija un formato de Excel valido" );
            }
        }
    }//GEN-LAST:event_btn_importar_ActionPerformed

    private void btn_calcular_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_ActionPerformed
        if( "".equals(txt_aceptacion_.getText()) ){
            JOptionPane.showMessageDialog(null, "Debe digitar el valor del nivel de aceptacion");
        }else{
            calcular();
        } 
    }//GEN-LAST:event_btn_calcular_ActionPerformed
    // ----------- FUNCIONES Y PROCEDIMIENTOS -------------------------------------------/////////////////////////////////
    public void calcular(){
        int numFilas = tabla_numerosAleatorios_.getRowCount();
        double suma = 0;
        for (int i = 0; i < numFilas; i++) {
            suma = suma+ Double.parseDouble( tabla_numerosAleatorios_.getValueAt(i, 1).toString() );
        }
        double r = suma/numFilas;
        System.out.println("La suma total de los numeros de la tabla: "+suma+" y r es: "+r);
        
        double aceptacion = Double.parseDouble( txt_aceptacion_.getText() );
        double filas = (double) numFilas;
        double raiz = Math.sqrt( 12 * filas);
        System.out.println(" raiz es: "+raiz+" y filas es: "+filas+" y aceptacion es "+aceptacion);
        double limiteSuperior = (0.5)+(aceptacion*(1/raiz));
        double limiteInferior = (0.5)-(aceptacion*(1/raiz));
        
        System.out.println("el limite inferior es: "+limiteInferior+" el numero r es: "+r+" y el limite superior es: "+limiteSuperior);
        
        if( r > limiteInferior && r < limiteSuperior ){
            JOptionPane.showMessageDialog(null, "El limite inferior es: "+limiteInferior+" el numero r es: "+r+" y el limite superior es: "+limiteSuperior+", \n por lo tanto el conjunto de numeros tienen un valor esperado de 0.5 o media por lo tanto son ACEPTADOS");
            etiq_resultado_.setText("ACEPTADO!, la media es: "+r);
            etiq_resultado_.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "el limite inferior es: "+limiteInferior+" el numero r es: "+r+" y el limite superior es: "+limiteSuperior+", \n por lo tanto el conjunto de numeros tienen un valor NO esperado de 0.5 o media por lo tanto son RECHAZADOS");
            etiq_resultado_.setText("RECHAZADO, la media es: "+r);
            etiq_resultado_.setVisible(true);
        }
        
    }
    
    public String importar(File archivo, JTable tablaD){
        
        String respuesta = "No se realizo con exito la importacion";
        DefaultTableModel modeloT = new DefaultTableModel();
        tablaD.setModel(modeloT);

        try{           
            wb = WorkbookFactory.create( new FileInputStream(archivo) );
            Sheet hoja = wb.getSheetAt(0);
            Iterator filaIterator = hoja.rowIterator();
            int indiceFila=-1;
            while( filaIterator.hasNext() ){
                indiceFila++;
                Row fila = (Row) filaIterator.next();
                Iterator columnaIterator = fila.cellIterator();
                Object[] listaColumna = new Object[5];
                int indiceColumna=-1;
                while( columnaIterator.hasNext() ){
                    indiceColumna++;
                    Cell celda = (Cell) columnaIterator.next();
                    if (indiceFila==0) {
                        modeloT.addColumn(celda.getStringCellValue());
                    } else {
                        if( celda!=null ){
                            switch( celda.getCellType() ){
                                case NUMERIC:
                                    listaColumna[indiceColumna] = (int) Math.round( celda.getNumericCellValue() );
                                    break;
                                case STRING:
                                    listaColumna[indiceColumna] = celda.getStringCellValue();
                                    break;
                                case BOOLEAN:
                                    listaColumna[indiceColumna] = celda.getBooleanCellValue();
                                    break;
                                default:
                                    listaColumna[indiceColumna] = celda.getDateCellValue();
                                    break;
                            }
                        }
                    }
                }
                if( indiceFila!=0 ){ modeloT.addRow(listaColumna); }
            }
            respuesta = "Importacion exitosa";
            tabla_numerosAleatorios_.setVisible(true);
            etiq_aceptacion_.setVisible(true);
            etiq_info_.setVisible(true);
            etiq_info2_.setVisible(true);
            btn_calcular_.setVisible(true);
            txt_aceptacion_.setVisible(true);
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "Error al importar datos desde archivo excel: -> "+e);
        }
        
        return respuesta;  
    }
    
    public void agregarFiltro(){     
        selecArchivo.setFileFilter( new FileNameExtensionFilter( "Excel (*.xls)","xls" )  );
        selecArchivo.setFileFilter( new FileNameExtensionFilter( "Excel (*.xlsx)","xlsx" )  );       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular_;
    public javax.swing.JButton btn_importar_;
    private javax.swing.JLabel etiq_aceptacion_;
    private javax.swing.JLabel etiq_info2_;
    private javax.swing.JLabel etiq_info_;
    private javax.swing.JLabel etiq_resultado_;
    private javax.swing.JLabel etiq_tituloMedia_;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla_numerosAleatorios_;
    private javax.swing.JTextField txt_aceptacion_;
    // End of variables declaration//GEN-END:variables
}
