/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.pruebas;

import javax.swing.JOptionPane;
import tipografias.Fuentes;

//librerias para exportar en excel
import java.io.*;
//import java.text.DecimalFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
//import org.apache.poi.hssf.usermodel.*;
//import org.apache.poi.xssf.usermodel.*;

//librerias que deberian ir en el controlador de excel
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author dark_
 */
public class poker extends javax.swing.JInternalFrame {

     // --- VARIABLES ------------crea variables para el modelo de la tabla y el tipo de fuente del formulario
    private final Fuentes tipoFuente; // para llamar el metodo de tipografias personalizadas

    Workbook wb; // para trabajar importar y/o exportar archivos en xls

    JFileChooser selecArchivo = new JFileChooser();
    File archivo;
    int contAccion = 0;
    double resultadoGlobal;
    /**
     * Creates new form poker
     */
    public poker() {
        initComponents();
        
        // SE PERSONALIZA TODO EL TEXTO CON FUENTES DEL PAQUETE TIPOGRAFIA
        tipoFuente = new Fuentes(); // crea tipo de fuente para usar atributos y procedimientos
        ///----------------///----- ETIQUETAS -----///---------------///
        etiq_tituloPoker_.setFont(tipoFuente.fuente(tipoFuente.GOD, 0, 24));
        etiq_resultado_.setFont(tipoFuente.fuente(tipoFuente.GOD, 0, 18));
        etiq_resultado_.setVisible(false);
        etiq_buscarChi1_.setVisible(false);
        etiq_buscarChi2_.setVisible(false);
        etiq_buscarChi3_.setVisible(false);
        etiq_colChi_.setVisible(false);
        etiq_filaChi_.setVisible(false);
        etiq_aceptacion_.setVisible(false);
        ///----------------///----- TABLAS -----///---------------///
        tabla_numerosAleatorios_.setVisible(false);
        ///----------------///----- TEXTO -----///---------------///
        txt_aceptacion_.setVisible(false);
        txt_valorChi_.setVisible(false);
        ///----------------///----- BOTONES -----///---------------///
        btn_calcular_.setVisible(false);
        btn_resultado_.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq_tituloPoker_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_numerosAleatorios_ = new javax.swing.JTable();
        btn_importar_ = new javax.swing.JButton();
        etiq_resultado_ = new javax.swing.JLabel();
        btn_calcular_ = new javax.swing.JButton();
        etiq_aceptacion_ = new javax.swing.JLabel();
        etiq_buscarChi1_ = new javax.swing.JLabel();
        etiq_buscarChi2_ = new javax.swing.JLabel();
        etiq_buscarChi3_ = new javax.swing.JLabel();
        etiq_filaChi_ = new javax.swing.JLabel();
        txt_aceptacion_ = new javax.swing.JTextField();
        btn_resultado_ = new javax.swing.JButton();
        etiq_colChi_ = new javax.swing.JLabel();
        txt_valorChi_ = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        etiq_tituloPoker_.setText("PRUEBA POKER");

        tabla_numerosAleatorios_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_numerosAleatorios_.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_numerosAleatorios_);

        btn_importar_.setText("IMPORTAR desde EXCEL");
        btn_importar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importar_ActionPerformed(evt);
            }
        });

        etiq_resultado_.setText("RESULTADO");

        btn_calcular_.setText("Calcular");
        btn_calcular_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_ActionPerformed(evt);
            }
        });

        etiq_aceptacion_.setText("Digite el nivel de aceptacion (solo numero no escribir %): ");

        etiq_buscarChi1_.setText("la columna es el numero mas cercano a:");

        etiq_buscarChi2_.setText("y la fila es el numero mas cercano a:");

        etiq_buscarChi3_.setText("Valor encontrado en tabla chi:");

        etiq_filaChi_.setText("fila M");

        btn_resultado_.setText("Resultado");
        btn_resultado_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultado_ActionPerformed(evt);
            }
        });

        etiq_colChi_.setText("col M");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(etiq_tituloPoker_))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiq_aceptacion_)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiq_buscarChi1_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiq_colChi_))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_aceptacion_, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_calcular_))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiq_buscarChi3_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_valorChi_, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_resultado_))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_importar_))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiq_buscarChi2_)
                        .addGap(18, 18, 18)
                        .addComponent(etiq_filaChi_))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiq_resultado_)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiq_tituloPoker_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_importar_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq_aceptacion_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_aceptacion_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_buscarChi1_)
                    .addComponent(etiq_colChi_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_buscarChi2_)
                    .addComponent(etiq_filaChi_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_buscarChi3_)
                    .addComponent(txt_valorChi_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resultado_))
                .addGap(18, 18, 18)
                .addComponent(etiq_resultado_)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_importar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importar_ActionPerformed

        contAccion++;
        if (contAccion == 1) {
            agregarFiltro();
        }

        if (selecArchivo.showDialog(null, "Seleccionar archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = selecArchivo.getSelectedFile();
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                JOptionPane.showMessageDialog(null, importar(archivo, tabla_numerosAleatorios_));
            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato de Excel valido");
            }
        }
    }//GEN-LAST:event_btn_importar_ActionPerformed

    private void btn_calcular_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_ActionPerformed
        if( "".equals(txt_aceptacion_.getText()) ){
            JOptionPane.showMessageDialog(null, "Debe digitar el valor del nivel de confianza/aceptacion");
        }else{
            calcular();
            double alfa = ( 100 - Double.parseDouble( txt_aceptacion_.getText() ) )/100;
            etiq_filaChi_.setText( String.valueOf( tabla_numerosAleatorios_.getRowCount()-1 ) );
            etiq_colChi_.setText( String.valueOf( alfa ) );
            etiq_filaChi_.setVisible(true);
            etiq_colChi_.setVisible(true);
            etiq_aceptacion_.setVisible(true);
            etiq_buscarChi1_.setVisible(true);
            etiq_buscarChi2_.setVisible(true);
            etiq_buscarChi3_.setVisible(true);
            txt_valorChi_.setVisible(true);
            btn_resultado_.setVisible(true);
        }
    }//GEN-LAST:event_btn_calcular_ActionPerformed

    private void btn_resultado_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultado_ActionPerformed
        if( "".equals(txt_valorChi_.getText()) ){
            JOptionPane.showMessageDialog(null, "Debe digitar el valor encontrado en tabla chi");
        }else{
            double valorTxt = Double.parseDouble( txt_valorChi_.getText() );
            if( valorTxt > resultadoGlobal ){
                JOptionPane.showMessageDialog(null, "El valor de la tablaChi es: "+valorTxt+" y es mayor que el valor encontrado: "+resultadoGlobal+", \n por lo tanto es RECHAZADO");
                etiq_resultado_.setText("RECHAZADO valor encontrado es de: "+resultadoGlobal);
                etiq_resultado_.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "El valor de la tablaChi es: "+valorTxt+" y es menor que el valor encontrado: "+resultadoGlobal+", \n por lo tanto es ACEPTADO");
                etiq_resultado_.setText("ACEPTADO! valor encontrado es de: "+resultadoGlobal);
                etiq_resultado_.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_resultado_ActionPerformed

// ----------- FUNCIONES Y PROCEDIMIENTOS -------------------------------------------/////////////////////////////////
    
    public void calcular() {

        ArrayList<String> stringImportados = new ArrayList<>();
        
        int numFilas = tabla_numerosAleatorios_.getRowCount();
        double filas = (double) numFilas;
        
        String sacarDecimal;
        //String[] partes;
        String Decimales;
        
        //////// --- APARTA LOS DECIMALES DE LOS NUMEROS QUE LLEGAN --- ////////
        for (int i = 0; i < numFilas; i++) {
            sacarDecimal = tabla_numerosAleatorios_.getValueAt(i, 1).toString();
            //System.out.println("saca el decimal: "+sacarDecimal);
            String[] partes = sacarDecimal.split("\\.");
            //System.out.println("parte entera: "+partes[0]);
           // System.out.println("parte decimal: "+partes[1]);
            Decimales = partes[1];
            stringImportados.add(Decimales);
        }
            
        double suma = 0;
        
        for (int i = 0; i < numFilas; i++) {
            suma = suma + Double.parseDouble( stringImportados.get(i) );
        }
        
        int promedio = (int) (suma/numFilas);
        
        int decimal = cuentaDigitos( promedio );
        
        System.out.println("el promedio es de: "+promedio);
        
        //////// --- RELLENA LOS NUMEROS CON CEROS SI FALTAN --- ////////
        
        if( decimal > 2 && decimal < 6 ){
            
            String rellenar = ""; 
            String aux;
            
            switch( decimal ){
                case 3:
                    for(int i = 0; i < numFilas; i++ ){
                
                        switch ( stringImportados.get(i).length() ) {
                            case 1:
                                rellenar = "00";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            case 2:
                                rellenar = "0";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            default:
                                break;
                        }
               
                    }
                    break;
                case 4:
                    for(int i = 0; i < numFilas; i++ ){
                
                        switch ( stringImportados.get(i).length() ) {
                            case 1:
                                rellenar = "000";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            case 2:
                                rellenar = "00";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            case 3:
                                rellenar = "0";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            default:
                                break;
                        }
               
                    }
                    break;
                case 5:
                    for(int i = 0; i < numFilas; i++ ){
                
                        switch ( stringImportados.get(i).length() ) {
                            case 1:
                                rellenar = "0000";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            case 2:
                                rellenar = "000";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            case 3:
                                rellenar = "00";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            case 4:
                                rellenar = "0";
                                aux = stringImportados.get(i);
                                aux = aux+rellenar;
                                stringImportados.set(i, aux);
                                break;
                            default:
                                break;
                        }
               
                    }
                    break;
                default:
                    break;
            }
            
            System.out.println("arreglo con relleno");
            
            for (int i = 0; i < numFilas; i++) {
                System.out.println(stringImportados.get(i));
            }
            
            //////// --- CONTAR duplas, triples, entre otros  --- ////////
            
            ArrayList<Integer> naturales    = new ArrayList<>();
            ArrayList<Integer> categorias3   = new ArrayList<>(); // categorias 3 decimales
            ArrayList<Integer> categorias4   = new ArrayList<>(); // categorias 4 decimales
            ArrayList<Integer> categorias5   = new ArrayList<>(); // categorias 5 decimales
            
            int posNatural;
            int auxPos;
            int auxCate;
            
            int todDifer;
            int unPar;
            int dosPares; 
            int tercia;
            int terciaPar;
            int poker;
            int quintilla;
            
            for (int h = 0; h < 10; h++) {
                naturales.add(0);
            }
            
            for (int h = 0; h < 3; h++) {
                categorias3.add(0);
            }
            
            for (int h = 0; h < 5; h++) {
                categorias4.add(0);
            }
            
            for (int h = 0; h < 7; h++) {
                categorias5.add(0);
            }
            
            switch ( decimal ) {
                
                case 3: /////   3 DECIMALES
                    
                    for (int i = 0; i < numFilas; i++) {
                        
                        todDifer    = 0;
                        unPar       = 0;
                        tercia      = 0;
                        
                        String revisar = stringImportados.get(i);
                        String[] arrRevisar = revisar.split("");
                        
                        for (int j = 0; j < revisar.length(); j++) {
                            posNatural = Integer.parseInt( arrRevisar[j] );
                            auxPos = naturales.get( posNatural );
                            naturales.set(posNatural , auxPos+1 );
                        }
                        
                        System.out.println("arreglo naturales con cantidad");
                        
                        for (int k = 0; k < 10; k++) {
                            System.out.println("numero: "+k+", cantidad: "+naturales.get(k) );
                            if( naturales.get(k) == 3 ){
                                tercia = 1;
                                unPar = 0;
                                break;
                            }
                            if( naturales.get(k) == 2 ){
                                unPar = 1;
                                break;
                            }
                        }
                        
                        if( unPar == 0 && tercia == 0  ){
                            todDifer = 1;
                        }
                        
                        auxCate = categorias3.get(0);
                        categorias3.set(0, auxCate+todDifer);
                        
                        auxCate = categorias3.get(1);
                        categorias3.set(1, auxCate+unPar);
                        
                        auxCate = categorias3.get(2);
                        categorias3.set(2, auxCate+tercia);
                        
                        for (int h = 0; h < 10; h++) {
                            naturales.set(h, 0);
                        }
                    }
                    
                    System.out.println("cantidad todos diferentes:  "+categorias3.get(0));
                    System.out.println("cantidad un par:            "+categorias3.get(1));
                    System.out.println("cantidad tercia:           "+categorias3.get(2));
                    
                    break;
                    
                case 4:   /////   4 DECIMALES
                    
                    for (int i = 0; i < numFilas; i++) {
                        
                        todDifer    = 0;
                        unPar       = 0;
                        dosPares    = 0;
                        tercia      = 0;
                        poker       = 0;
                        
                        String revisar = stringImportados.get(i);
                        String[] arrRevisar = revisar.split("");
                        
                        for (int j = 0; j < revisar.length(); j++) {
                            posNatural = Integer.parseInt( arrRevisar[j] );
                            auxPos = naturales.get( posNatural );
                            naturales.set(posNatural , auxPos+1 );
                        }
                        
                        System.out.println("arreglo naturales con cantidad");
                        
                        for (int k = 0; k < 10; k++) {
                            System.out.println("numero: "+k+", cantidad: "+naturales.get(k) );
                            if( naturales.get(k) == 4 ){
                                poker = 1;
                                break;
                            }
                            if( naturales.get(k) == 3 ){
                                tercia = 1;
                                break;
                            }
                            if( naturales.get(k) == 2 ){
                                unPar++;
                                if( unPar == 2 ){
                                    break; 
                                }
                            }
                        }
                        
                        if( unPar == 2 ){
                            unPar = 0;
                            dosPares = 1;
                        }
                        
                        if( unPar == 0 && dosPares == 0 && tercia == 0 && poker == 0 ){
                            todDifer = 1;
                        }
                        
                        auxCate = categorias4.get(0);
                        categorias4.set(0, auxCate+todDifer);
                        
                        auxCate = categorias4.get(1);
                        categorias4.set(1, auxCate+unPar);
                        
                        auxCate = categorias4.get(2);
                        categorias4.set(2, auxCate+dosPares);
                        
                        auxCate = categorias4.get(3);
                        categorias4.set(3, auxCate+tercia);
                        
                        auxCate = categorias4.get(4);
                        categorias4.set(4, auxCate+poker);
                        
                        for (int h = 0; h < 10; h++) { // reinicia el conteo de numeros
                            naturales.set(h, 0);
                        }
                    }
                    
                    System.out.println("cantidad todos diferentes:  "+categorias4.get(0));
                    System.out.println("cantidad un par:            "+categorias4.get(1));
                    System.out.println("cantidad dos pares:         "+categorias4.get(2));
                    System.out.println("cantidad tercia:           "+categorias4.get(3));
                    System.out.println("cantidad poker  :           "+categorias4.get(4));
                    
                    break;
                    
                case 5:  /////   5 DECIMALES
                    
                    for (int i = 0; i < numFilas; i++) {
                        
                        todDifer    = 0;
                        unPar       = 0;
                        dosPares    = 0;
                        tercia      = 0;
                        terciaPar   = 0;
                        poker       = 0;
                        quintilla   = 0;
                        
                        String revisar = stringImportados.get(i);
                        String[] arrRevisar = revisar.split("");
                        
                        for (int j = 0; j < revisar.length(); j++) {
                            posNatural = Integer.parseInt( arrRevisar[j] );
                            auxPos = naturales.get( posNatural );
                            naturales.set(posNatural , auxPos+1 );
                        }
                        
                        System.out.println("arreglo naturales con cantidad");
                        
                        for (int k = 0; k < 10; k++) {
                            System.out.println("numero: "+k+", cantidad: "+naturales.get(k) );
                            
                            if( naturales.get(k) == 5 ){
                                quintilla = 1;
                                break;
                            }
                            if( naturales.get(k) == 4 ){
                                poker = 1;
                                break;
                            }
                            if( naturales.get(k) == 3 ){
                                tercia = 1;
                            }
                            if( naturales.get(k) == 2 ){
                                unPar++;
                                if( unPar == 2 ){
                                    break; 
                                }
                            }
                        }
                        
                        if( unPar == 2 ){
                            unPar = 0;
                            dosPares = 1;
                        }
                        
                        if( tercia == 1 && unPar == 1 ){
                            tercia = 0;
                            unPar = 0;
                            terciaPar = 1;
                        }
                        
                        if( unPar == 0 && dosPares == 0 && tercia == 0 && terciaPar == 0 && poker == 0 && quintilla == 0 ){
                            todDifer = 1;
                        }
                        
                        auxCate = categorias5.get(0);
                        categorias5.set(0, auxCate+todDifer);
                        
                        auxCate = categorias5.get(1);
                        categorias5.set(1, auxCate+unPar);
                        
                        auxCate = categorias5.get(2);
                        categorias5.set(2, auxCate+dosPares);
                        
                        auxCate = categorias5.get(3);
                        categorias5.set(3, auxCate+tercia);
                        
                        auxCate = categorias5.get(4);
                        categorias5.set(4, auxCate+terciaPar);
                        
                        auxCate = categorias5.get(5);
                        categorias5.set(5, auxCate+poker);
                        
                        auxCate = categorias5.get(6);
                        categorias5.set(6, auxCate+quintilla);
                        
                        for (int h = 0; h < 10; h++) { // reinicia el conteo de numeros
                            naturales.set(h, 0);
                        }
                    }
                    
                    System.out.println("cantidad todos diferentes:  "+categorias5.get(0));
                    System.out.println("cantidad un par:            "+categorias5.get(1));
                    System.out.println("cantidad dos pares:         "+categorias5.get(2));
                    System.out.println("cantidad tercia:            "+categorias5.get(3));
                    System.out.println("cantidad tercia y par:      "+categorias5.get(4));
                    System.out.println("cantidad poker:             "+categorias5.get(5));
                    System.out.println("cantidad quintilla:         "+categorias5.get(6));
                    
                    break;
                default:
                    break;
            }
            
            //////// --- SE CALCULAR CON LAS PROBABILIDADES  --- ////////
            
            /*int posNatural;
            int auxPos;
            int auxCate;*/
            
            double todDiferProba;
            double unParProba;
            double dosParesProba; 
            double terciaProba;
            double terciaParProba;
            double pokerProba;
            double quintillaProba;
            
            double resultado = 0;
            
            switch( decimal ){
                case 3:
                    
                    todDiferProba   = 0.72 * numFilas;
                    unParProba      = 0.27 * numFilas;
                    terciaProba     = 0.01 * numFilas;
                    
                    resultado = resultado + ( ( Math.pow( todDiferProba - categorias3.get(0) , 2) ) / todDiferProba );
                    resultado = resultado + ( ( Math.pow( unParProba    - categorias3.get(1) , 2) ) / unParProba );
                    resultado = resultado + ( ( Math.pow( terciaProba   - categorias3.get(2) , 2) ) / terciaProba );
                    
                    resultadoGlobal = resultado;
                    
                    JOptionPane.showMessageDialog(null, "EL resultado calculado es: "+resultado);
                    
                    System.out.println("resultado es: "+resultado);
                    
                    break;
                case 4:
                    
                    todDiferProba   = 0.5040 * numFilas;
                    unParProba      = 0.4320 * numFilas;
                    dosParesProba   = 0.0270 * numFilas;
                    terciaProba     = 0.0360 * numFilas;
                    pokerProba      = 0.0010 * numFilas;
                    
                    resultado = resultado + ( ( Math.pow( todDiferProba - categorias4.get(0) , 2) ) / todDiferProba );
                    resultado = resultado + ( ( Math.pow( unParProba    - categorias4.get(1) , 2) ) / unParProba );
                    resultado = resultado + ( ( Math.pow( dosParesProba - categorias4.get(2) , 2) ) / dosParesProba );
                    resultado = resultado + ( ( Math.pow( terciaProba   - categorias4.get(3) , 2) ) / terciaProba );
                    resultado = resultado + ( ( Math.pow( pokerProba    - categorias4.get(4) , 2) ) / pokerProba );
                    
                    resultadoGlobal = resultado;
                    
                    JOptionPane.showMessageDialog(null, "EL resultado calculado es: "+resultado);
                    
                    System.out.println("resultado es: "+resultado);
                    
                    break;
                case 5:
                    
                    todDiferProba   = 0.3024 * numFilas;
                    unParProba      = 0.3040 * numFilas;
                    dosParesProba   = 0.1080 * numFilas;
                    terciaProba     = 0.0090 * numFilas;
                    terciaParProba  = 0.0720 * numFilas;
                    pokerProba      = 0.0045 * numFilas;
                    quintillaProba  = 0.0001 * numFilas;
                    
                    resultado = resultado + ( ( Math.pow( todDiferProba     - categorias5.get(0) , 2) ) / todDiferProba );
                    resultado = resultado + ( ( Math.pow( unParProba        - categorias5.get(1) , 2) ) / unParProba );
                    resultado = resultado + ( ( Math.pow( dosParesProba     - categorias5.get(2) , 2) ) / dosParesProba );
                    resultado = resultado + ( ( Math.pow( terciaProba       - categorias5.get(3) , 2) ) / terciaProba );
                    resultado = resultado + ( ( Math.pow( terciaParProba    - categorias5.get(4) , 2) ) / terciaParProba );
                    resultado = resultado + ( ( Math.pow( pokerProba        - categorias5.get(5) , 2) ) / pokerProba );
                    resultado = resultado + ( ( Math.pow( quintillaProba    - categorias5.get(6) , 2) ) / quintillaProba );
                    
                    resultadoGlobal = resultado;
                    
                    JOptionPane.showMessageDialog(null, "EL resultado calculado es: "+resultado);
                    
                    System.out.println("resultado es: "+resultado);
                    
                    break;
                default:
                    break;
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "La cantidad de decimales debe ser entre 3 a 5" );
        }
        
    }
    
    private static int cuentaDigitos(int numero) // se certifica con esto de que sean numeros en la celda de la tabla
    {
        int digitos = 0;
        while( numero !=0 ) //cuenta los digitos de un numero
            {
                numero = numero/10;
                digitos++;
            }

        return digitos;
    } 
    
    public String importar(File archivo, JTable tablaD) {

        String respuesta = "No se realizo con exito la importacion";
        DefaultTableModel modeloT = new DefaultTableModel();
        tablaD.setModel(modeloT);

        try {
            wb = WorkbookFactory.create(new FileInputStream(archivo));
            Sheet hoja = wb.getSheetAt(0);
            Iterator filaIterator = hoja.rowIterator();
            int indiceFila = -1;
            while (filaIterator.hasNext()) {
                indiceFila++;
                Row fila = (Row) filaIterator.next();
                Iterator columnaIterator = fila.cellIterator();
                Object[] listaColumna = new Object[5];
                int indiceColumna = -1;
                while (columnaIterator.hasNext()) {
                    indiceColumna++;
                    Cell celda = (Cell) columnaIterator.next();
                    if (indiceFila == 0) {
                        modeloT.addColumn(celda.getStringCellValue());
                    } else {
                        if (celda != null) {
                            switch (celda.getCellType()) {
                                case NUMERIC:
                                    listaColumna[indiceColumna] = (int) Math.round(celda.getNumericCellValue());
                                    break;
                                case STRING:
                                    listaColumna[indiceColumna] = celda.getStringCellValue();
                                    break;
                                case BOOLEAN:
                                    listaColumna[indiceColumna] = celda.getBooleanCellValue();
                                    break;
                                default:
                                    listaColumna[indiceColumna] = celda.getDateCellValue();
                                    break;
                            }
                        }
                    }
                }
                if (indiceFila != 0) {
                    modeloT.addRow(listaColumna);
                }
            }
            respuesta = "Importacion exitosa";
            tabla_numerosAleatorios_.setVisible(true);
            etiq_aceptacion_.setVisible(true);
            txt_aceptacion_.setVisible(true);
            btn_calcular_.setVisible(true);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al importar datos desde archivo excel: -> " + e);
        }

        return respuesta;
    }

    public void agregarFiltro() {
        selecArchivo.setFileFilter(new FileNameExtensionFilter("Excel (*.xls)", "xls"));
        selecArchivo.setFileFilter(new FileNameExtensionFilter("Excel (*.xlsx)", "xlsx"));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular_;
    public javax.swing.JButton btn_importar_;
    private javax.swing.JButton btn_resultado_;
    private javax.swing.JLabel etiq_aceptacion_;
    private javax.swing.JLabel etiq_buscarChi1_;
    private javax.swing.JLabel etiq_buscarChi2_;
    private javax.swing.JLabel etiq_buscarChi3_;
    private javax.swing.JLabel etiq_colChi_;
    private javax.swing.JLabel etiq_filaChi_;
    private javax.swing.JLabel etiq_resultado_;
    private javax.swing.JLabel etiq_tituloPoker_;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla_numerosAleatorios_;
    private javax.swing.JTextField txt_aceptacion_;
    private javax.swing.JTextField txt_valorChi_;
    // End of variables declaration//GEN-END:variables
}
